project_id = "zwpjpvqcepbxlddqvjff"

[auth]
site_url = "https://www.getvendorflow.app"
additional_redirect_urls = [
  "https://www.getvendorflow.app/**",
  "https://getvendorflow.app/**",
]

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.claude-ai]
verify_jwt = false

[functions.get-receipt]
verify_jwt = false

[functions.search-event]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-terminal-connection-token]
verify_jwt = false

[functions.stripe-create-payment-intent]
verify_jwt = false

[functions.public-trailer-menu]
verify_jwt = false

[functions.place-online-order]
verify_jwt = false
