project_id = "vtobvrsbmymcdfwzcigo"

[functions.claude-ai]
verify_jwt = false

[functions.get-receipt]
verify_jwt = false

[functions.search-event]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.confirm-payment]
verify_jwt = false

[functions.admin-manage-user]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-team-member]
verify_jwt = false
